### ISSUE TITLE
Add support for Forge twitter account

### ISSUE THREAD

**Issue by Soypete** [forgeutah/tweet_automated_bot#13]
add a discord slash command and role for interacting with the forge twitter account via discord. 

this is an example of the go west slash command
![Screen Shot 2022-03-25 at 4 42 19 PM](https://user-images.githubusercontent.com/34897832/160211368-fa26f642-7b5d-4b99-90fa-e976a16c0c0a.png)

## TODO:

- [ ] Add forge twitter account API credentials (see @Soypete)
- [x] add them to existing twitter client or to a new twitter client
- [ ] update the twitter send command to distinguish between accounts
- [ ] add new slash command with the name `twitter_forge`
- [ ] add role for accessing this discord bot
- [ ] add logic give write permissions based on role
